### ISSUE TITLE
fork from Mobile-Detect from GitHub instead of Google Code

### ISSUE THREAD

**Issue by serbanghita** [suncat2000/php-mobile-detect#1]
https://github.com/serbanghita/Mobile-Detect - we've now moved the repository to GitHub and you can fork straight from the project. I would love to integrate the composer support. 

Does the Mobile_Detect class need to be in /lib/Mobile/ ?

**Comment by suncat2000** [comment]
Hi!
Great news!

`Does the Mobile_Detect class need to be in /lib/Mobile/ ?`

No, I thought that as more attractive ))

Composer supports several class autoload way: PSR-0, classmap generation and files. [composer man](http://getcomposer.org/doc/04-schema.md#autoload)
PSR-0 can perform according autoload PEAR-style non-namespaced convention.

You can do as you see fit!
Please report me, when you add composer support, I will update MobileDetectBundle.

Thanks
