### ISSUE TITLE
Update mobiledetect ?

### ISSUE THREAD

**Issue by nMustaki** [suncat2000/php-mobile-detect#2]
Hello,

do you plan on regularly updating the mobiledetect source or should I manage my own package if I want to stay up to date ?

Thansk !

**Comment by suncat2000** [comment]
Hello,

My plan in the future to use the [Mobile-Detect](https://github.com/serbanghita/Mobile-Detect), but serbanghita has not added a repository to packagist.org, to manage through composer.phar

You can ask him to add composer.json (he planned to do it) or need update this repository. You can do PR. Unfortunately now I have no time(((

**Comment by nMustaki** [comment]
Hi,
I have added an issue to Serbanghita, I think it makes more sense if the package is made from the original repo.

I created a first draft from you composer.json for Serbanghita, so thanks :-)

**Comment by serbanghita** [comment]
@suncat2000 @nMustaki thanks for pointing this out! I'm currently documenting the process here: https://github.com/serbanghita/Mobile-Detect/issues/18

**Comment by suncat2000** [comment]
Hi, I did a little refactoring.
Now, [MobileDetectBundle](https://github.com/suncat2000/MobileDetectBundle) uses the original class of [Mobile_Detect](https://github.com/serbanghita/Mobile-Detect) from serbanghita.
But there is bug, I described it in this [issue#18](https://github.com/serbanghita/Mobile-Detect/issues/18).
I think it will fixed quickly

**Comment by suncat2000** [comment]
Bug, fixed!
